# Generated by Django 4.2.4 on 2023-10-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_kunle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kunle',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
